services:
  - type: web
    name: placement-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Decision_Tree.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
